apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: velocap-api:latest
          ports:
            - containerPort: 3000 # Ensure this port matches the port your NestJS app runs on

---
apiVersion: v1
kind: Service
metadata:
  name: nest-app-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000 # Specify an unused node port
  selector:
    app: nest-app
