apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocap-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocap-api
  template:
    metadata:
      labels:
        app: velocap-api
    spec:
      containers:
        - name: nest-app
          image: velocap-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 # Ensure this port matches the port your NestJS app runs on

---
apiVersion: v1
kind: Service
metadata:
  name: velocap-api-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000 # Specify an unused node port
  selector:
    app: velocap-api
