apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocap-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocap-app
  template:
    metadata:
      labels:
        app: velocap-app
      annotations:
        kubernetes.io/change-cause: "Update image at $(date +'%Y-%m-%d %H:%M:%S')"
    spec:
      containers:
        - name: velocap-app-deployment
          image: velocap-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: velocap-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: velocap-app
