apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
      annotations:
        kubernetes.io/change-cause: "Update image at $(date +'%Y-%m-%d %H:%M:%S')"
    spec:
      containers:
        - name: velocap-app-deployment
          image: angular-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: angular-app
